import type { AppBootstrapPayload } from '@/types/desktop';

const fallbackPaths = {
  workspaceRoot: '[workspace-root]',
  userKurisuRoot: '[user-home]/.kurisu',
  programDataRoot: '[program-data]/kurisu',
  projectHash: '[project-hash]',
} as const;

export const fallbackBootstrap: AppBootstrapPayload = {
  productName: 'Kurisu Desktop',
  currentMode: 'code',
  currentLocale: 'en',
  locales: [
    { code: 'en', name: 'English', nativeName: 'English' },
    { code: 'ru', name: 'Russian', nativeName: 'Русский' },
  ],
  workspaceRoot: fallbackPaths.workspaceRoot,
  tracks: [],
  compatibilityGoals: [],
  capabilityLanes: [],
  adoptionPatterns: [],
  recentSessions: [],
  activeTurns: [],
  activeArenaSessions: [],
  recoverableTurns: [],
  projectSummary: {
    hasHistory: false,
    filePath: '',
    content: '',
    timestampText: '',
    timeAgo: '',
    overallGoal: '',
    currentPlan: '',
    totalTasks: 0,
    doneCount: 0,
    inProgressCount: 0,
    todoCount: 0,
    pendingTasks: [],
    timestampUtc: '0001-01-01T00:00:00Z',
  },
  kurisuCompatibility: {
    projectRoot: fallbackPaths.workspaceRoot,
    defaultContextFileName: 'QWEN.md',
    settingsLayers: [],
    surfaceDirectories: [],
    commands: [],
    skills: [],
  },
  kurisuRuntime: {
    projectRoot: fallbackPaths.workspaceRoot,
    globalKurisuDirectory: fallbackPaths.userKurisuRoot,
    runtimeBaseDirectory: fallbackPaths.userKurisuRoot,
    runtimeSource: 'default-home',
    projectDataDirectory: `${fallbackPaths.userKurisuRoot}/projects/${fallbackPaths.projectHash}`,
    chatsDirectory: `${fallbackPaths.userKurisuRoot}/projects/${fallbackPaths.projectHash}/chats`,
    historyDirectory: `${fallbackPaths.userKurisuRoot}/history/${fallbackPaths.projectHash}`,
    contextFileNames: ['QWEN.md'],
    contextFilePaths: [`${fallbackPaths.workspaceRoot}/QWEN.md`],
    folderTrustEnabled: false,
    isWorkspaceTrusted: true,
    workspaceTrustSource: '',
    approvalProfile: {
      defaultMode: 'default',
      confirmShellCommands: false,
      confirmFileEdits: false,
      allowRules: [],
      askRules: [],
      denyRules: [],
    },
    modelName: '',
    embeddingModel: '',
    currentLocale: 'en',
    currentLanguage: 'English',
    chatCompression: {
      contextPercentageThreshold: null,
    },
    telemetry: {
      enabled: false,
      target: 'none',
      otlpEndpoint: '',
      otlpProtocol: '',
      logPrompts: false,
      outfile: '',
      useCollector: false,
    },
    checkpointing: false,
  },
  kurisuModels: {
    defaultModelId: '',
    embeddingModelId: '',
    selectedAuthType: 'openai',
    availableModels: [],
  },
  kurisuTools: {
    sourceMode: 'native-contracts',
    totalCount: 0,
    allowedCount: 0,
    askCount: 0,
    denyCount: 0,
    tools: [],
  },
  kurisuNativeHost: {
    registeredCount: 0,
    implementedCount: 0,
    readyCount: 0,
    approvalRequiredCount: 0,
    tools: [],
  },
  kurisuAuth: {
    selectedType: 'openai',
    selectedScope: 'user',
    displayName: 'OpenAI-compatible',
    status: 'missing-credentials',
    model: '',
    endpoint: '',
    apiKeyEnvironmentVariable: 'OPENAI_API_KEY',
    hasApiKey: false,
    lastError: '',
    lastAuthenticatedAtUtc: null,
  },
  kurisuMcp: {
    totalCount: 0,
    connectedCount: 0,
    disconnectedCount: 0,
    missingCount: 0,
    tokenCount: 0,
    servers: [],
  },
  kurisuChannels: {
    isServiceRunning: false,
    serviceProcessId: null,
    serviceStartedAtUtc: '',
    serviceUptimeText: '',
    supportedTypes: [],
    channels: [],
  },
  kurisuExtensions: {
    totalCount: 0,
    activeCount: 0,
    linkedCount: 0,
    missingCount: 0,
    extensions: [],
  },
  kurisuWorkspace: {
    git: {
      isGitAvailable: false,
      isRepository: false,
      worktreeSupported: false,
      repositoryRoot: '',
      currentBranch: '',
      currentCommit: '',
      gitVersion: '',
      managedSessionCount: 0,
      managedWorktreesRoot: '',
      worktrees: [],
      history: {
        isInitialized: false,
        historyDirectory: '',
        checkpointCount: 0,
        currentCheckpoint: '',
        recentCheckpoints: [],
      },
    },
    discovery: {
      gitAware: false,
      hasQwenIgnore: false,
      candidateFileCount: 0,
      visibleFileCount: 0,
      gitIgnoredCount: 0,
      qwenIgnoredCount: 0,
      qwenIgnorePatternCount: 0,
      contextFiles: [],
      sampleVisibleFiles: [],
      sampleGitIgnoredFiles: [],
      sampleQwenIgnoredFiles: [],
    },
  },
  kurisuProviderPresets: [],
};
